# Generated by Django 4.2 on 2023-04-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlists_Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.TextField()),
                ('song_id', models.TextField()),
            ],
            options={
                'db_table': 'playlists_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'songs   ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs_Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.TextField()),
                ('playlist_id', models.TextField()),
            ],
            options={
                'db_table': 'songs_playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('representation', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
