# Generated by Django 4.2 on 2023-10-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('playlist_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.TextField(blank=True, null=True)),
                ('song_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlists_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongsPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.TextField(blank=True, null=True)),
                ('playlist_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'songs_playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('client_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('current_score', models.FloatField(default=-1)),
                ('last_best_score', models.DateTimeField(auto_now=True)),
                ('time_since_best_score', models.FloatField(default=0)),
                ('slow_improvement_flag', models.IntegerField(default=0)),
                ('current_labels', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('suggestions_scores', models.JSONField(default=dict)),
                ('users_scores', models.JSONField(default=dict)),
                ('feedback_songs', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Playlists_Songs',
        ),
        migrations.DeleteModel(
            name='Songs_Playlists',
        ),
        migrations.AlterModelTable(
            name='songs',
            table='songs',
        ),
    ]
