# Generated by Django 4.2 on 2023-10-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muz', '0002_playlists_playlistssongs_songsplaylists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='users',
            field=models.JSONField(default=list),
        ),
    ]
