# Generated by Django 4.2 on 2023-10-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muz', '0003_communitymodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='last_best_score',
            field=models.FloatField(default=0),
        ),
    ]
