# Generated by Django 4.2 on 2023-10-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muz', '0004_alter_communitymodel_last_best_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='last_best_score',
            field=models.FloatField(default=1),
        ),
    ]
